# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master", "v1", "release" ]
    tags: ['*']
  pull_request:
    branches: [ "master", "v1", "release" ]

jobs:
  build-21:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.1.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew shadowJar

      - name: Upload JarFile
        uses: actions/upload-artifact@v7.0.0
        with:
          name: jar
          path: ./build/libs/VRCNicoNicoPlaylistConverter-1.0-SNAPSHOT-all.jar

      - name: Upload BatchFile (for Windows)
        uses: actions/upload-artifact@v7.0.0
        with:
          name: batch1
          path: ./run-batch/VRCNicoNicoPlaylist_start.bat

      - name: Upload BatchFile (for Linux)
        uses: actions/upload-artifact@v7.0.0
        with:
          name: batch2
          path: ./run-batch/VRCNicoNicoPlaylist_start_linux.sh

  release:
    needs: [build-21]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download JarFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v8.0.1
        with:
          name: jar

      - name: Download BatchFile (for Windows)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v8.0.1
        with:
          name: batch1

      - name: Download BatchFile (for Linux)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v8.0.1
        with:
          name: batch2

      - name: Create Release Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mv ./VRCNicoNicoPlaylist_start.bat start.bat
          mv ./VRCNicoNicoPlaylist_start_linux.sh start_forLinux.sh
          zip VRCNicoNicoPlaylistConverter.zip VRCNicoNicoPlaylistConverter-1.0-SNAPSHOT-all.jar start.bat start_forLinux.sh
        shell: bash

      - name: Linux Bash Setup Test
        if: startsWith(github.ref, 'refs/tags/')
        run: |        
          chmod +x ./start_forLinux.sh
          screen -UAmdS test ./start_forLinux.sh
          sleep 15s
          if [ -d ./tools ]; then
            echo "Tools Folder OK"
            if [ -d ./tools/jdk-21.0.2 ]; then
              echo "OpenJDK OK"
              if [ -d ./tools/javafx-sdk-21.0.10 ]; then
                echo "JavaFX OK"
              else
                exit 1
              fi
            fi
          else
            exit 1
          fi

        shell: bash

      - name: Create PKGBUILD File
        if: startsWith(github.ref, 'refs/tags/')
        id: create_pkgbuild
        run: |
          echo -e "pkgname=VRCNicoNicoPlayListConverter\npkgver=$(echo "${{ github.ref }}" | sed -E "s,^refs/tags/,,")\npkgrel=1\npkgdesc=\"This tool converts playlists from Nico Nico Douga into the playlist format used by VRC's video player.\"\narch=('x86_64')\nurl=\"https://nicovrc.net\"\nlicense=('MIT')\ndepends=('jdk21-openjdk')\nsource=( \"$pkgname::git+https://github.com/nicovrc-net/nico-proxy_forVRC.git#branch=master\")\nsha256sums=('SKIP')\n\nbuild() {\n    cd \"\$srcdir/\$pkgname\"\n    chmod +x gradlew\n    ./gradlew shadowJar\n}\n\npackage() {\n    cd \"\$srcdir/\$pkgname\"\n    \n    echo -e \"#!/bin/bash\\njava -Duser.timezone=Asia/Tokyo -Xms4G -Xmx4G -jar /usr/share/$pkgname/VRCNicoNicoPlaylistConverter-1.0-SNAPSHOT-all.jar\" > ./temp-start.sh\n\n    install -Dm644 \"build/libs/VRCNicoNicoPlaylistConverter-1.0-SNAPSHOT-all.jar\" \"\$pkgdir/usr/share/\$pkgname/VRCNicoNicoPlaylistConverter-1.0-SNAPSHOT-all.jar"\n    install -Dm755 "./temp-start.sh" "\$pkgdir/usr/bin/\$pkgname"\n\n    find "\$pkgdir/usr/share/\$pkgname\" -type f -exec file {} \; | grep ELF | cut -d: -f1 | while read -r elf; do\n        strip --strip-all \"\$elf\" || true\n    done\n\n}" > ./PKGBUILD
        shell: bash

      - name: Create deb Package
        if: startsWith(github.ref, 'refs/tags/')
        id: create_deb_package
        run: |
          INPUT_VERSION="$(echo "${{ github.ref }}" | sed -E "s,^refs/tags/,,")"
          
          mkdir -p ./deb-package
          mkdir -p ./deb-package/usr/share/VRCNicoNicoPlayListConverter
          mkdir -p ./deb-package/usr/bin
          
          mkdir -p ./deb-package/DEBIAN
          
          echo -e "Package: VRCNicoNicoPlayListConverter\nVersion: $INPUT_VERSION-1\nArchitecture: amd64\nMaintainer: Chino Nanami <tino_nanami@7mi.site>\nDescription: This tool converts playlists from Nico Nico Douga into the playlist format used by VRC's video player.\nDepends: openjdk-21-jdk " > ./deb-package/DEBIAN/control
          
          echo -e "#!/bin/bash\nif [ -x /usr/bin/VRCNicoNicoPlayListConverter ]; then\nelse\n  rm /usr/share/VRCNicoNicoPlayListConverter -fr\n  rm /usr/bin/VRCNicoNicoPlayListConverter" > ./deb-package/DEBIAN/postrm
          chmod +x ./deb-package/DEBIAN/postrm
          
          cp ./VRCNicoNicoPlaylistConverter-1.0-SNAPSHOT-all.jar ./deb-package/usr/share/VRCNicoNicoPlayListConverter
          
          echo -e "#!/bin/bash\njava -Duser.timezone=Asia/Tokyo -Xms4G -Xmx4G -jar /usr/share/VRCNicoNicoPlayListConverter/VRCNicoNicoPlaylistConverter-1.0-SNAPSHOT-all.jar" > ./deb-package/usr/bin/VRCNicoNicoPlayListConverter
          chmod +x ./deb-package/usr/bin/VRCNicoNicoPlayListConverter
          
          fakeroot dpkg-deb --build $WORK ./deb-package

        shell: bash

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          body: |
            - 出力先にiwaSync prefab追加
          draft: false
          prerelease: true

      - name: Upload JarFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./VRCNicoNicoPlaylistConverter.zip
          asset_name: VRCNicoNicoPlaylistConverter.zip
          asset_content_type: application/java-archive

      - name: Upload deb package File
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./deb-package.deb
          asset_name: VRCNicoNicoPlaylistConverter.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload PKGBUILD File
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PKGBUILD
          asset_name: PKGBUILD
          asset_content_type: text/plain


      - name: Delete File
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            jar